### ISSUE TITLE
Slow data fetch and display

### ISSUE THREAD

**Issue by chaosLegacy** [raynor85/react-native-material-selectize#16] opened 2018-09-16 10:11 UTC
Hi,
I'm using this library for displaying a list of languages I have about 373 languages in a JSON file. the problem is that in my device (I'm using Samsung Galaxy s7) it takes too much to load about 5 to 6sec and if I select a language it will take around 6 to 7sec to display the chips every time. I was wondering if there is a way accelerate this process like limiting the data display for a certain a number and if the user decides to search a particular language only then it will fetch the data from the whole JSON.

Thank you

**Comment by raynor85** [comment] 2018-09-16 13:29
If you hard code your array of languages in a data structure and you pass it as a prop (without involving the network), do you still experience the delay?
Nothing prevents you from transforming this data structure and passing it to the component in chunks.

**Comment by raynor85** [comment] 2018-09-16 18:28
Uhm.. can you please write down a basic example to replicate the issue?

**Comment by raynor85** [comment] 2018-10-14 16:42
I think the problem is related to the inefficiency of the ScrollView. I will investigate and probably swap it with a FlatList, thank you for rising the issue.

**Comment by raynor85** [comment] 2019-02-10 00:51
It should be fixed with https://github.com/raynor85/react-native-material-selectize/tree/v1.15.0

**Closed** 2019-02-10 00:54 UTC
